apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tidb-tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tidb-tools
    spec:
      containers:
        - name: tidb-tools
          image: kolbe/tidb-tools
          command: ['/bin/bash']
          ports:
            - containerPort: 8080
