apiVersion: v1
kind: Pod
metadata:
  name: tidb-tools
spec:
    #  nodeSelector:
    #use: tidb-tools

  containers:
  - image: kolbe/tidb-tools
    name: tidb-tools
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
        # name must match the volume name below
        - name: tidb-secret
          mountPath: /etc/tidb-secret
        - name: cluster-secret
          mountPath: /etc/cluster-secret
    env:
        - name: MYSQL_TCP_PORT
          value: "4000"

  volumes:
    - name: tidb-secret
      secret:
        secretName: CLUSTER_NAME-tidb-client-secret
    - name: cluster-secret
      secret:
        secretName: CLUSTER_NAME-cluster-client-secret

